Mixdjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('combo/',include('combo.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

combo/urls.py
from django.contrib import admin
from django.urls import path,include

from .import views





app_name = "combo"
urlpatterns = [
   	path('',views.list, name='list'),
   	path('new/',views.new, name ='new'),
   	path('<int:pk>/poll/',views.polldetail, name='polldetail'),
   	path('<int:question_id>/results/', views.results, name='results'),
   	path('<int:pk>/vote/',views.vote, name='vote'),
   	path('<int:pk>/edit/', views.edit, name='edit'),
	path('<int:pk>/',views.detail, name='detail'),	
	path('poll/',views.poll, name='poll'),
	
	



]

combo/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to='combo/image/',default="")
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title



class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

combo/forms.py
from django import forms
from .models import Post

class BasicForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','text','image')

combo/views.py
from django.shortcuts import  get_object_or_404,render,redirect
from django.template import loader
from django.utils import timezone
from django.urls import reverse
from .models import Post,Question,Choice
from django.http import HttpResponse,HttpResponseRedirect
from .forms import BasicForm


# Create your views here.


def list(request):
	posts = Post.objects.order_by('-published_date')[:5]
	return render(request,'combo/list.html',{'posts': posts })

"""def detail(request):
    question = Post.objects.order_by('-published_date')[:5]
    return render(request, 'combo/detail.html', {'question': question})"""

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'combo/detail.html', {'post': post })


def new(request):
	if request.method == "POST":
		form = BasicForm(request.POST,request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.pub_date = timezone.now()
			post.save()
		posts = Post.objects.filter(published_date=timezone.now()).order_by('published_date')
		return render(request,'combo/list.html' ,{'posts': posts })

            #return redirect('combo:detail', pk=post.pk)
	else:
		form = BasicForm()
		return render(request, 'combo/edit.html', {'form': form})


def edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form = BasicForm(request.POST, request.FILES,instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.pub_date = timezone.now()
			post.save()
			return redirect('detail', pk=post.pk)
	else:
		form = BasicForm(instance=post)
	return render(request, 'combo/edit.html', {'form': form})

#poll
def poll(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	#template = loader.get_template('combo/poll_index.html')
	context = {
        'latest_question_list': latest_question_list,
    }
	return render(request,'combo/poll_index.html',context)


def polldetail(request, pk):
	try:
		question = Question.objects.get(pk=pk)
	except Question.DoesNotExist:
		raise Http404("Question does not exist")
	return render(request, 'combo/poll_detail.html', {'question': question})



def results(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'combo/poll_results.html', {'question': question})




def vote(request, pk):
	question = get_object_or_404(Question, pk=pk)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'combo/poll_detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
        })
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('combo:results', args=(question.id,)))

combo/templates/combo/detail.html
{% extends 'combo/index.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date  %}
            <div class="date">
                {{ post.published_date  }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'combo:edit' post.pk %}" ><span class="glyphicon glyphicon-pencil"></span></a>
        <h2>{{ post.author }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>-->
        {% if error_message %}
        <p> {{ error_message }}</p>
        {% endif %}
        {% if post.image %}
            <img src="{{ post.image.url}}" height="250" width="400">
        {% endif %}
        <form action="{% url 'combo:vote' post.pk %}" method="post">
            {% csrf_token %}
            {% for choice in post.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <input type="submit" value="Done">
        </form>

    </div>    
{% endblock %}

combo/templates/combo/edit.html
{% extends 'combo/index.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

combo/templates/combo/index.html
{% load static %}
<html>
    <head>
        <title>Djangocomb</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="page-header">

            <a href="{% url 'combo:new' %}"  class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="{% url 'combo:list' %}">Djangocomb</a></h1>
            <h1><a href="{% url 'combo:poll' %}">Poll</a></h1>


        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

combo/templates/combo/list.html
{% extends 'combo/index.html' %}
{% block content %}
    {% for post in posts %}
        
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h2><a href="{% url 'combo:detail' post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
            {% if post.image %}
            <p><img src="{{ post.image.url}}" height="250" width="400"></p>
            {% endif %}
            <br>
            <ul>
            {% for choice in post.choice_set.all %}
                <li>{{ choice.votes }} {{ choice.choice_text}}{{ choice.choice_text|pluralize  }} </li>
            {% endfor %}
            </ul>
        </div>
        
    {% endfor %}
{% endblock %}

combo/templates/combo/poll_detail.html
{% extends 'combo/index.html'%}

{% block content %}
<h1>{{ question.question_text }}</h1>

	{% if error_message %}
	<p>
		<strong>{{ error_message }}</strong>
	</p>
	{% endif %}

		<form action="{% url 'combo:vote' question.id %}" method="post">
			{% csrf_token %}
			{% for choice in question.choice_set.all %}
    		<h2><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"></h2>
    		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
			{% endfor %}
			<input type="submit" value="Vote">
		</form>
{% endblock %}

combo/templates/combo/poll_index.html
{% extends 'combo/index.html' %}
    {% block content %}
            {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
                <h2><li><a href="{% url 'combo:polldetail' question.id %}">{{ question.question_text }}</a></li></h2>
            {% endfor %}
            </ul>
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
            {% endblock %}
            

 

combo/templates/combo/poll_results.html
{% extends 'combo/index.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

	<ul>
		{% for choice in question.choice_set.all %}
    	<li ><h4>{{ choice.choice_text }} : {{ choice.votes }} vote{{ choice.votes|pluralize }}</h4></li>
		{% endfor %}
	</ul>

	<h4><a href="{% url 'combo:polldetail' question.id %}">Vote again?</a></h4>

{% endblock %}